# .github/workflows/gretl-analysis-nodejs.yml
name: GRETL Jobs Analysis (Node.js)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches: [ main ]
  #repository_dispatch:
  #  types: [gretl-jobs-updated]

jobs:
  analyze-gretl-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Meta Repository
      uses: actions/checkout@v4
      with:
        path: gretljobs-meta
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout GRETL Jobs Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/gretljobs
        path: gretljobs
        token: ${{ secrets.GRETL_JOBS_TOKEN || secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: gretljobs-meta/package-lock.json

    - name: Install dependencies
      run: |
        cd gretljobs-meta
        npm ci

    - name: Run GRETL Jobs Analysis
      run: |
        cd gretljobs-meta
        npm run analyze
      env:
        GRETL_JOBS_DIR: ../gretljobs
        OUTPUT_FILE: GRETL_Jobs_Overview.md
        DEBUG: true

    - name: Run tests (optional)
      run: |
        cd gretljobs-meta
        npm test
      continue-on-error: true

    - name: Validate generated documentation
      run: |
        cd gretljobs-meta
        # Check if file was generated
        if [ ! -f "GRETL_Jobs_Overview.md" ]; then
          echo "❌ Documentation file not generated"
          exit 1
        fi

        # Check file size
        size=$(wc -c < "GRETL_Jobs_Overview.md")
        if [ $size -lt 100 ]; then
          echo "❌ Documentation file too small ($size bytes)"
          exit 1
        fi

        echo "✅ Documentation generated successfully ($size bytes)"

        # Show preview
        echo "=== Documentation Preview ==="
        head -30 "GRETL_Jobs_Overview.md"

    - name: Commit and push documentation
      run: |
        cd gretljobs-meta
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add GRETL_Jobs_Overview.md

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "docs: update GRETL jobs analysis ($(date +%Y-%m-%d %H:%M))"
          git push
        fi

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: gretl-jobs-documentation
        path: |
          gretljobs-meta/GRETL_Jobs_Overview.md
        retention-days: 30

    - name: Create GitHub Release (on version tags)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: GRETL Jobs Analysis ${{ github.ref }}
        body: |
          Automated GRETL jobs analysis documentation

          - Generated: $(date)
          - Jobs analyzed: See attached documentation
        draft: false
        prerelease: false

